services:
  - type: web
    id: vizag-web
    name: vizagraithubazaar
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: vizag-bazaar-db
          property: connectionString

databases:
  - id: vizag-db
    name: vizag-bazaar-db
    databaseName: vizag_bazaar
    user: vizag_user
    plan: free
